product = {
  brand: "abc",
  name: "xyz",
  rating: 4.3,
  rating_count: 100,
  D_price: 599,
  MRP: 1500,
  discount: 60,
  size: [38, 40, 42, 44],
  details: `Black checked opaque Casual shirt ,has a spread collar, button placket, 1 patch pocket, long roll-up sleeves, curved hem`,
  size: `Regular Fit`,
  fit: `The model(height 6') is wearing a size 40`,
  material: `100% Cotton`,
  care: `Machine-wash`,
  specifications: [
    [`Sleeve Length`, `Long Sleeves`],
    [`Fit`, `Regular Fit`],
    [`Occasion `,`Casual`],
    [`Hemline`,`Curved`],
    [`Placket Length`,`Full`],
    [`Pocket Type`,`Patch`],
    [`Transparency`,`Opaque`],
    [`Surface Styling`,`Chest Pocket`],
    [`Collar`,`Spread Collar`],
    [`Print or Pattern Type`,`Other Checks`],
    [`Number of Pockets`,`1`],
    [`Cluff`,`Button`],
    [`Weave Patter`,`Twill`],
    [`Main Trend`,`New Basics`]
  ],
};
